### ISSUE TITLE
Feature request: self-play analysis board (without the engine!)

### ISSUE THREAD

**Issue by neongreen** [hiveboardgame/hive#236]
Recently I've had a number of cases when I was uncertain about the rules and thought "man, would be nice to set up this position at HiveGame and see which moves are legal".

Right now it doesn't seem to be possible.

A lichess-style "setup board" editor would be ideal, but even something like a mode where I can make moves for both sides would already be very useful.

**Comment by klautcomputing** [comment]
To a degree this feature already exists, but it's at a rudimentary stage: https://hivegame.com/analysis it currently requires you to play a game turn by turn and doesn't yet let you freely set up a board, is that what you mean by "without the engine"? Because we will need the engine to then answer your question about "which moves are legal".

If you want to learn more about what we are working on at the moment please join us on discord https://discord.gg/jw7sJepE

**Comment by neongreen** [comment]
Oh, the analysis link you posted is exactly what I want — I just didn’t know it existed. Is it exposed anywhere in the menu?

**Comment by neongreen** [comment]
And no, by “which moves are legal” I just meant the rules of the game, which the analysis link already seems to implement — each turn it shows me where the selected piece can move.

**Comment by klautcomputing** [comment]
> Oh, the analysis link you posted is exactly what I want — I just didn’t know it existed. Is it exposed anywhere in the menu?

You can get to it from the end of a game, by clicking on the 🔬 But we don't feel it's ready yet, so no it's not yet advertised widely. Once it has a couple of more features we will advertise it more widely.

**Comment by neongreen** [comment]
Ok, thanks!
